baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'HTML Viewer'
custom_css = ["css/styles.css"]
custom_js = ["js/index.js"]
disableKinds = ["taxonomy", "term"]

[taxonomies]
    category = "categories"
    tag = "tags"